# Generated by Django 4.0.5 on 2022-07-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['target_weight']},
        ),
    ]
