# Generated by Django 4.0.5 on 2022-07-22 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_alter_company_options_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['symbol']},
        ),
    ]
